name: lab

mgmt:
  network: clab
  ipv4-subnet: 172.20.20.0/24

topology:
  kinds:
    ceos:
      image: arista/ceos64-lab:4.28.5M
      env:
        CLAB_MGMT_VRF: mgmt
        EOS_PLATFORM: ceoslab
        SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT: "1" 

  nodes:
    R1:
      kind: ceos
      startup-config: configs/R1.cfg  
    R2:
      kind: ceos
      startup-config: configs/R2.cfg
    R3:
      kind: ceos
      startup-config: configs/R3.cfg
    R4:
      kind: ceos
      startup-config: configs/R4.cfg
    R5:
      kind: ceos
      startup-config: configs/R5.cfg
    S1:
      kind: ceos
      startup-config: configs/S1.cfg
    S2:
      kind: ceos
      startup-config: configs/S2.cfg
    S3:
      kind: ceos
      startup-config: configs/S3.cfg
    S4:
      kind: ceos
      startup-config: configs/S4.cfg
    Web:
      kind: linux
      image: ubuntu-web
      exec:
        - bash -c "apt-get install -y vim iproute2"
        - bash -c "ip addr add 203.0.113.10/30 dev eth1"
        - bash -c "ip -6 addr add 2115::1/64 dev eth1"
        - bash -c "ip link set eth1 up"
        - bash -c "ip route add 10.0.0.0/8 via 203.0.113.9" 
        - bash -c "ip -6 route add 2101::/64 via 2115::2"
        - bash -c "ip -6 route add 2102::/64 via 2115::2"
        - bash -c "ip -6 route add 2103::/64 via 2115::2"
    NMAS:
      kind: linux
      image: ubuntu-host
      exec:
        - bash -c "apt-get install -y vim iproute2 openssh-client"
        - bash -c "ip addr add 10.10.4.254/24 dev eth1"
        - bash -c "ip link set eth1 up"
        - bash -c "ip route add 203.0.0.0/8 via 10.10.4.3"
        - bash -c "ip route add 10.10.40.0/24 via 10.10.4.1"
    H1:
      kind: linux
      image: ubuntu-host
      exec:
        - bash -c "apt-get install -y vim iproute2"
        - bash -c "ip addr add 10.10.0.3/28 dev eth1"
        - bash -c "ip -6 addr add 2101::3/64 dev eth1"
        - bash -c "ip link set eth1 up"
        - bash -c "ip route add 203.0.0.0/8 via 10.10.0.1" 
        - bash -c "ip -6 route add 2102::/64 via 2101::1"
        - bash -c "ip -6 route add 2103::/64 via 2101::1"
        - bash -c "ip -6 route add 2115::/64 via 2101::1"
    H2:
      kind: linux
      image: ubuntu-host
      exec:
        - bash -c "apt-get install -y vim iproute2"
        - bash -c "ip addr add 10.10.1.3/28 dev eth1"
        - bash -c "ip -6 addr add 2102::3/64 dev eth1"
        - bash -c "ip link set eth1 up"
        - bash -c "ip route add 203.0.0.0/8 via 10.10.1.1" 
        - bash -c "ip -6 route add 2101::/64 via 2102::1"
        - bash -c "ip -6 route add 2103::/64 via 2102::1"
        - bash -c "ip -6 route add 2115::/64 via 2102::1"
    H3:
      kind: linux
      image: ubuntu-host
      exec:
        - bash -c "apt-get install -y vim iproute2"
        - bash -c "ip addr add 10.10.0.4/28 dev eth1"
        - bash -c "ip -6 addr add 2101::4/64 dev eth1"
        - bash -c "ip link set eth1 up"
        - bash -c "ip route add 203.0.0.0/8 via 10.10.0.1" 
        - bash -c "ip -6 route add 2102::/64 via 2101::1"
        - bash -c "ip -6 route add 2103::/64 via 2101::1"
        - bash -c "ip -6 route add 2115::/64 via 2101::1"
    H4:
      kind: linux
      image: ubuntu-host
      exec:
        - bash -c "apt-get install -y vim iproute2"
        - bash -c "ip -6 addr add 2103::3/64 dev eth1"
        - bash -c "ip link set eth1 up"
        - bash -c "ip -6 route add 2101::/64 via 2103::1"
        - bash -c "ip -6 route add 2102::/64 via 2103::1"
        - bash -c "ip -6 route add 2115::/64 via 2103::1"

  links:
    - endpoints: [ R5:eth1, R3:eth1 ]
    - endpoints: [ R5:eth2, R4:eth1 ]
    - endpoints: [ R3:eth2, R4:eth2 ]
    - endpoints: [ R3:eth3, S3:eth1 ]
    - endpoints: [ R4:eth3, S4:eth1 ]
    - endpoints: [ R1:eth1, S3:eth2 ]
    - endpoints: [ R1:eth2, S1:eth1 ]
    - endpoints: [ R2:eth1, S4:eth2 ]
    - endpoints: [ R2:eth2, S2:eth1 ]
    - endpoints: [ S3:eth4, S4:eth4 ]
    - endpoints: [ S1:eth4, S2:eth4 ]
    - endpoints: [ S3:eth3, NMAS:eth1 ]
    - endpoints: [ S1:eth2, H1:eth1 ]
    - endpoints: [ S1:eth3, H2:eth1 ]
    - endpoints: [ S2:eth2, H3:eth1 ]
    - endpoints: [ S2:eth3, H4:eth1 ]
    - endpoints: [ R5:eth4, Web:eth1 ]
